version: 2
jobs:
  build:
    working_directory: /go/src/github.com/VividCortex/multitick
    docker: 
      - image: circleci/golang:1.13.3
    environment:
      GO111MODULE: "off"

    steps:
      - checkout
      - run: go vet ./...
      - run: go test -race ./...
